kind: pipeline
type: docker
name: default

trigger:
  branch:
    include:
    - main
  event:
    include:
    - push
    - pull_request

steps:
- name: build-image
  image: plugins/docker:18
  settings:
    auto_tag: true
    repo: benschumacher/s3ql
    username: benschumacher
    password: 
      from_secret: DOCKER_ACCESS_TOKEN

